### ISSUE TITLE
Sphinx-doc .. code-block:: does not work

### ISSUE THREAD

**Issue by Paradinight** [bcit-ci/CodeIgniter#5283]
https://www.codeigniter.com/user_guide/general/urls.html?highlight=htaccess#removing-the-index-php-file

htaccess example looks a little bit broken

**Comment by jim-parry** [comment]
Agreed. There are a few more, reported on twitter. I haven't had a chance to tackle them :( but I will soon if no one else takes them on :)

**Comment by narfbg** [comment]
Kinda saw this coming ... #5188, #5191.

**Comment by mamat-rahmat** [comment]
I think i found the bug. There is two colon (::) before the code-block. May i make a PR?
Also, the suitable lexer for .htaccess code is this http://pygments.org/docs/lexers/#pygments.lexers.configs.ApacheConfLexer

**Comment by mamat-rahmat** [comment]
> Agreed. There are a few more, reported on twitter

@jim-parry which are the other? I tried to search other code-block but those seems ok.

**Comment by jim-parry** [comment]
Removing the double colon at the end of line 45 eliminates the sphinx error, and the htaccess block is formatted correctly, but grayed.

Also changing the directive, from "console" to "apache" appears to be the correct choice, with the htaccess directive color-coded.

@mamat-rahmat Thank you, and yes, go for a PR :)

ps - the other errors reported on twitter seem to have been fixed with recent changes, although there are still a number of Sphinx hiccups in the CodeIgniter4 user guide.

**Comment by dervos** [comment]
While it's fixed; the error is still present on the [documentation](https://www.codeigniter.com/user_guide/general/urls.html?highlight=apache#removing-the-index-php-file).

**Comment by narfbg** [comment]
Yea, docs are in the same repo as the actual code and the fix was commited after the last release and, so ...

**Comment by dervos** [comment]
I see, the docs will get some love with the next release :)
